version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    groups:
      junit-dependencies:
        patterns:
          - "org.junit.*"
          - "junit:junit"
          - "org.opentest4j:*"
      gradle-dependencies:
        patterns:
          - "*"
    ignore:
      - dependency-name: "org.junit.*"
        update-types: ["version-update:semver-major"]
      - dependency-name: "junit:junit"
        update-types: ["version-update:semver-major"]
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      github-actions-dependencies:
        patterns:
          - "*"
